dev/README.md
Add initial directory structure
=> Add initial directory structure

dev/README.md, sdk/README.md
=> Updated directory structure

artifacts/gcp/vick-init-gcp.sh, artifacts/global/apim-configs/api-manager.xml, artifacts/global/apim-configs/carbon.xml, artifacts/global/apim-configs/datasources/master-datasources.xml, artifacts/global/apim-configs/registry.xml, artifacts/global/apim-configs/user-mgt.xml, artifacts/global/vick-apim-gw.yaml, artifacts/global/vick-apim-pub-store-ingress.yaml, artifacts/global/vick-apim-pub-store.yaml, artifacts/global/vick-control-plane-deploy.sh, artifacts/global/vick-ns-init.yaml
=> Add VICK control plane deployment YAMLs

README.md, artifacts/vick.yaml, cmd/controller/main.go, pkg/controller/cell/cell.go, pkg/controller/cell/resources/constants.go, pkg/controller/cell/resources/meta.go, pkg/controller/cell/resources/network.go, pkg/controller/service/resources/constants.go, pkg/controller/service/resources/meta.go
Add initial cell level network isolation
=> Add cell level network isolation

artifacts/gcp/mandatory.yaml, artifacts/gcp/vick-init-gcp.sh
=>  Add nginx ingress YAML

system/controller/artifacts/crd-cell.yaml, system/controller/artifacts/crd-service.yaml, system/controller/cmd/controller/main.go, system/controller/pkg/apis/vick/v1alpha1/cell_types.go, system/controller/pkg/apis/vick/v1alpha1/service_types.go, system/controller/pkg/controller/cell/cell.go, system/controller/pkg/controller/service/resources/deployment.go, system/controller/pkg/controller/service/resources/meta.go, system/controller/pkg/controller/service/resources/service.go, system/controller/pkg/controller/service/service.go
Add cell, service status tracking for kubectl
=>  Add cell, service status tracking for kubectl

system/controll-plane/cell/gateway/README.md, system/controll-plane/cell/gateway/artifacts/microgateway-deployment.yaml, system/controll-plane/cell/gateway/artifacts/microgateway-service.yaml, system/controll-plane/cell/gateway/dockerfiles/init-container/Dockerfile, system/controll-plane/cell/gateway/dockerfiles/init-container/files/init.sh, system/controll-plane/cell/gateway/dockerfiles/microgateway-container/Dockerfile
Add cell gateway deployment and docker files with the initial guide.
=> Add cell gateway deployment

system/controll-plane/global/vick-control-plane-deploy.sh, system/scripts/kubeadm/mandatory.yaml, system/scripts/kubeadm/vick-init-kubeadm.sh
=>  Refactor APIM configuration location and Add K8s setup scripts for kubeadm

.gitignore, system/controll-plane/cell/components/global-api-updater/pom.xml, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/controller/API.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/controller/ApiDefinition.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/controller/Cell.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/controller/RestConfig.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/ApiCreateRequest.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Endpoint.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Label.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Method.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Parameter.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/PathDefinition.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/PathsMapping.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/ProductionEndpoint.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/exceptions/APIException.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/internals/ConfigManager.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/Constants.java, system/controll-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/RequestProcessor.java, system/controll-plane/cell/gateway/dockerfiles/init-container/Dockerfile, system/controll-plane/cell/gateway/dockerfiles/init-container/files/init.sh
> Add global api creation for microgateway.
=> Add global api creation for microgateway

samples/cell/example-cell.yaml, system/controller/pkg/apis/vick/register.go, system/controller/pkg/controller/cell/cell.go, system/controller/pkg/controller/cell/resources/meta.go, system/controller/pkg/controller/cell/resources/service.go, system/controller/pkg/controller/service/resources/deployment.go
Add cell services domain name injection to service containers
=> Add cell services domain name injection to service containers

system/control-plane/global/vick-apim-persistent-volume-claim.yaml, system/control-plane/global/vick-apim-persistent-volumes.yaml, system/control-plane/global/vick-control-plane-cleanup.sh, system/control-plane/global/vick-control-plane-deploy.sh
=> Add APIM related volumes and volume claims.

system/control-plane/global/components/org.wso2.vick.auth.extensions/pom.xml, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/api/handler/VickSignedJWTInjectionHandler.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTGenerator.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTValidator.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/km/VickExtendedKeyManagerImpl.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/km/VickExtendedKeyValidationHandler.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/util/Utils.java
* Support for signedJWT based authentication for APIs
* Custom JWT Token Generator to issue signedJWT to be consumed by micro gateways
* Custom synapse handler to manipulate 'Authorization' header when sending signed JWT issued by STS to downstream cell gateways
=> Add extensions related to global STS functionality

build/target/vick.yaml, system/controller/artifacts/01-cluster-role.yaml
- Add missing cluster-role to yaml
=> Add missing cluster-role to yaml

samples/cell/example-cell.yaml, system/controller/artifacts/08-config.yaml, system/controller/cmd/controller/main.go, system/controller/pkg/apis/vick/register.go, system/controller/pkg/controller/cell/resources/network.go, system/controller/pkg/controller/gateway/gateway.go, system/controller/pkg/controller/gateway/resources/config.go, system/controller/pkg/controller/gateway/resources/constants.go, system/controller/pkg/controller/gateway/resources/deployment.go
Add cell gateway config injection from vick-system's configmap
=> Add cell gateway config injection from vick-system's configmap

system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTGenerator.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/km/VickExtendedKeyManagerImpl.java
=> Fix expiry time in JWT issued by global STS

system/control-plane/global/apim-configs/gw/api-manager.xml, system/control-plane/global/apim-configs/gw/identity/identity.xml, system/control-plane/global/apim-configs/gw/resources/api_templates/velocity_template.xml, system/control-plane/global/apim-configs/pub-store/api-manager.xml, system/control-plane/global/apim-configs/pub-store/identity/identity.xml, system/control-plane/global/apim-configs/pub-store/resources/api_templates/velocity_template.xml
=> Add config file changes required for Global STS functionality

system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Label.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/PathsMapping.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/Constants.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/RequestProcessor.java
Improve swagger API definition of global API updater. 
* Updated swagger version
* Error handling improvements
* Enhance the code to add API definitions with multiple methods
=> Improve swagger API definition of global API updater

system/controller/artifacts/08-config.yaml, system/controller/pkg/controller/gateway/resources/constants.go
=> Update cell gateway configmap

system/control-plane/global/apim-configs/gw/log4j.properties, system/control-plane/global/status-dashboard/conf/deployment.yaml, system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-control-plane-cleanup.sh, system/control-plane/global/vick-control-plane-deploy.sh
=> Alter the volume claim delete order.

system/control-plane/global/apim-configs/gw/api-manager.xml, system/control-plane/global/apim-configs/gw/identity/identity.xml
=> Update configuration files to be in sync with APIM 2.6.0 in the global control plane

system/scripts/kubeadm/vick-init-kubeadm.sh
> add the command to turn off swap.
=> Add swapoff command

build/target/vick.yaml, system/controller/artifacts/08-config.yaml, system/controller/cmd/controller/main.go, system/controller/pkg/controller/sts/config/config.go, system/controller/pkg/controller/sts/resources/config.go, system/controller/pkg/controller/sts/resources/deployment.go, system/controller/pkg/controller/sts/resources/meta.go, system/controller/pkg/controller/sts/sts.go
Add config injection to sts container
=> Add config injection to sts container

build/target/vick.yaml, system/controller/artifacts/04-crd-cell.yaml, system/controller/artifacts/05-crd-gateway.yaml, system/controller/artifacts/07-crd-service.yaml, system/controller/pkg/apis/vick/v1alpha1/cell_types.go, system/controller/pkg/apis/vick/v1alpha1/gateway_types.go, system/controller/pkg/apis/vick/v1alpha1/service_types.go, system/controller/pkg/controller/cell/cell.go, system/controller/pkg/controller/gateway/gateway.go, system/controller/pkg/controller/service/service.go
=> Update CRD status fields 

system/controller/pkg/controller/gateway/resources/config.go, system/controller/pkg/controller/gateway/resources/meta.go
Update cell gateway api config to include gateway hostname
=> Update cell gateway api config to include gateway hostname

system/controller/pkg/controller/sts/resources/constants.go, system/controller/pkg/controller/sts/resources/deployment.go
Add cell name env variable to sts container
=> Add cell name env variable to sts container

system/controller/pkg/controller/cell/resources/gateway.go, system/controller/pkg/controller/cell/resources/meta.go
Update resource name generation format to <cell-name>--<resource>
=> Update resource name generation format to <cell-name>--<resource>

system/scripts/kubeadm/kubeadm-setup.sh, system/scripts/kubeadm/vick-init-kubeadm.sh
=> Add kubeadmin setup script.

system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-apim-pub-store.yaml
=> Update APIM docker image version for VICK Control plane

system/control-plane/cell/components/global-api-updater/pom.xml, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/internals/ConfigManager.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/Constants.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/RequestProcessor.java, system/control-plane/cell/components/global-api-updater/src/main/resources/log4j2.properties
Enhance logging for api updater jar.
=> Enhance logging for api updater

system/scripts/kubeadm/kubeadm-setup.sh
=> Removed debug information.

system/scripts/kubeadm/kubeadm-setup.sh
=> Enable sudo for all the commands.

system/control-plane/cell/gateway/dockerfiles/microgateway-container/Dockerfile
=> Enable debug logs for cell gateway

build/target/vick.yaml, system/control-plane/cell/components/global-api-updater/src/main/resources/log4j2.properties, system/control-plane/cell/gateway/artifacts/microgateway-deployment.yaml, system/controller/artifacts/08-config.yaml
Change docker id and update log4j2 file for microgateway init container.
=> Change docker id and update log4j2 file for microgateway init container.

system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTBuilder.java, system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-apim-pub-store.yaml
=> Add keyType claim to STS token

system/control-plane/global/components/Dockerfile, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTBuilder.java, system/control-plane/global/components/org.wso2.vick.auth.extensions/src/main/java/org/wso2/vick/auth/jwt/VickSignedJWTGenerator.java, system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-apim-pub-store.yaml
$subject to avoid caching issues at APIM Gateway
=> Increase STS token validity to 20mins

system/control-plane/global/apim-configs/pub-store/log4j.properties, system/control-plane/global/vick-apim-persistent-volume-claim-local.yaml, system/control-plane/global/vick-apim-persistent-volumes-local.yaml, system/control-plane/global/vick-apim-pub-store.yaml, system/control-plane/global/vick-control-plane-deploy.sh, system/scripts/kubeadm/kubeadm-cleanup.sh, system/scripts/kubeadm/kubeadm-setup.sh
=> Add kubeadm clean up script and kubeadm setup scrip fixes.

samples/cell/example-cell.yaml, system/controller/pkg/controller/service/resources/constants.go, system/controller/pkg/controller/service/resources/meta.go
Add app label and containerPort to enable tracing
=> Add app label and containerPort to enable tracing

system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/Endpoint.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/SandboxEndpoint.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/Constants.java
Adding sandbox endpoint to fix jwt token issue
=> Adding sandbox endpoint to fix jwt token issue

system/controller/artifacts/08-config.yaml
=> Update STS configmap

system/scripts/kubeadm/kubeadm-setup.sh, system/scripts/kubeadm/vick-init-kubeadm.sh
=> Add Istio installation.

system/control-plane/cell/components/cell-sts/Dockerfile, system/control-plane/cell/components/cell-sts/create-docker-image.sh, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/VickCellSTSServer.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellOutboundAuthorizationService.java, system/controller/artifacts/08-config.yaml
=> Improve docker image building script for Cell STS

build/target/vick.yaml, system/controller/artifacts/09-controller.yaml, system/controller/build.sh, system/controller/pkg/controller/sts/resources/constants.go
Change vick-controller docker repository
=>  Change vick-controller docker repository

build/target/vick.yaml
=> Change APIM base url to point to the pub store K8s service

system/control-plane/cell/components/cell-sts/src/main/resources/sidecar-outbound-interception.yaml
=> Add sample envoy filter for cell outbound interception

system/scripts/kubeadm/kubeadm-setup.sh
=> Add the GPG key for Docker

system/controller/artifacts/08-config.yaml, system/controller/pkg/controller/gateway/config/config.go, system/controller/pkg/controller/gateway/gateway.go, system/controller/pkg/controller/gateway/resources/config.go, system/controller/pkg/controller/gateway/resources/constants.go, system/controller/pkg/controller/gateway/resources/deployment.go
Add setup config to gateway init container
=> Add setup config to gateway init container

system/scripts/kubeadm/kubeadm-cleanup.sh, system/scripts/kubeadm/kubeadm-setup.sh
=> Update setup scripts

system/control-plane/global/apim-configs/gw/carbon.xml, system/control-plane/global/apim-configs/gw/security/Owasp.CsrfGuard.Carbon.properties, system/control-plane/global/apim-configs/gw/tomcat/catalina-server.xml, system/control-plane/global/components/create-apim-docker-image.sh, system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-control-plane-deploy.sh
$subject and minor improvement to VICK APIM docker image building script.
=> Add configs required to run APIM on 443

system/scripts/kubeadm/kubeadm-cleanup.sh, system/scripts/kubeadm/kubeadm-setup.sh
Backup .kube/config file and Add vick yaml to setup script
=> Backup .kube/config file and Add vick yaml to setup script

system/control-plane/global/vick-control-plane-deploy.sh
=> Remove pub-store deployment.

system/control-plane/global/apim-configs/gw/security/Owasp.CsrfGuard.Carbon.properties
=> Whitelist OIDC Logout endpoint in CSRF properties

system/scripts/kubeadm/kubeadm-setup.sh
=> Fix setup script help command

system/control-plane/global/mysql-deployment.yaml, system/control-plane/global/mysql-persistent-volumes-local.yaml
=> Add new label to the node.

system/scripts/kubeadm/kubeadm-setup.sh
Update vick-setup script to force copy the kube config
=> Update vick-setup script to force copy the kube config

system/controller/artifacts/08-config.yaml
=> Pass through the authorization header to the services via micro gateway

system/control-plane/global/vick-control-plane-deploy.sh, system/scripts/kubeadm/kubeadm-cleanup.sh
=> Add SP ingress.

samples/cell/example-cell.yaml, system/control-plane/global/vick-apim-gw-ingress.yaml, system/control-plane/global/vick-apim-pub-store-ingress.yaml
Update gateway and pubstore ingress
=> Update gateway and pubstore ingress

system/control-plane/global/vick-control-plane-deploy.sh, system/scripts/kubeadm/service-nodeport.yaml
=> Add external ingress-ip

build/target/vick.yaml
Update vick.yaml with new config
=> Update vick.yaml with new config

samples/cell/hr-app/sample-employee-cell.yaml, samples/cell/hr-app/sample-hr-cell.yaml, samples/cell/hr-app/sample-stock-cell.yaml, system/scripts/kubeadm/kubeadm-setup.sh
> Add sample HR application cell definitions.
=>  Add sample HR app cells 

samples/cell/hr-app/sample-employee-cell.yaml, samples/cell/hr-app/sample-hr-cell.yaml, samples/cell/hr-app/sample-stock-cell.yaml, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/ApiCreateRequest.java
=> Update hr application

Makefile
Add basic makefile for the build
=> Add basic makefile for the build

samples/employee-portal/hr/Dockerfile, samples/employee-portal/hr/hrservice.bal, samples/employee-portal/portal/employee/Dockerfile, samples/employee-portal/portal/employee/employeeservice.bal, samples/employee-portal/portal/salary/Dockerfile, samples/employee-portal/portal/salary/salaryservice.bal, samples/employee-portal/stock-options/Dockerfile, samples/employee-portal/stock-options/stockservice.bal
Add sample employee portal backend
=> Add sample employee portal backend

system/control-plane/global/vick-control-plane-deploy.sh
=> Add kubectl wait to GW deployment.

system/controller/pkg/controller/cell/resources/constants.go, system/controller/pkg/controller/cell/resources/envoy_filter.go, system/controller/pkg/controller/sts/resources/deployment.go, system/controller/pkg/controller/sts/resources/service.go
Update envoyfilter to intercept both inbound and outbound traffic
=> Update envoyfilter to intercept both inbound and outbound traffic

system/control-plane/global/components/auth/Dockerfile
=> Change source docker image for VICK Global APIM

system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellInboundInterceptorService.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellInterceptorService.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellOutboundInterceptorService.java, system/control-plane/cell/components/cell-sts/src/main/resources/log4j2.properties
* Add cell name as a parameter in logs
* Refactor the cell STS code
=> Improve logging in cell STS

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/public/index.html, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/AppLayout.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/microService.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview.js
First, cut of react basic layout implementation.
=> Create app basic layout

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/.eslintignore, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/.eslintrc.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/pom.xml, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/App.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/AppLayout.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/Cell.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/MicroService.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/Overview.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/SignIn.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/Tracing.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/TracingSearch.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/TracingTimeline.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/utils/tracing/Constants.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/utils/tracing/Span.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/utils/tracing/Span.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/utils/tracing/TracingUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/utils/tracing/TracingUtils.test.js
> Add the ESLint plugin and fix minor issues.
> This aims towards adding a linting tool and fix the issues that the linting tool will fail on. Also, this changes the navigation to a router based navigation as well.
> Add ESLint as the linting tool. Remove the custom logic used for changing the pages and use the React Router for navigation.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> NPM 6.4.1
> N/A
=> Add ESLint and Fix minor issues

Gopkg.lock, Makefile, system/controller/pkg/controller/gateway/resources/config_test.go, system/controller/pkg/controller/gateway/resources/deployment_test.go, system/controller/pkg/controller/gateway/resources/service_test.go, system/controller/pkg/controller/service/resources/deployment_test.go, system/controller/pkg/controller/service/resources/service_test.go, system/controller/pkg/controller/sts/resources/config_test.go, system/controller/pkg/controller/sts/resources/deployment_test.go, system/controller/pkg/controller/sts/resources/service_test.go
Add initial go test coverage report generation to the build.
Add basic test cases for controller resource generation
=> Add unit tests for controller resource generation

system/controller/pkg/controller/cell/resources/envoy_filter_test.go, system/controller/pkg/controller/cell/resources/gateway_test.go, system/controller/pkg/controller/cell/resources/network_test.go, system/controller/pkg/controller/cell/resources/service_test.go, system/controller/pkg/controller/cell/resources/token_service_test.go
Add unit test for cell resources
=> Add unit test for cell resources

system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/beans/request/ApiCreateRequest.java, system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/utils/Constants.java, system/control-plane/cell/gateway/dockerfiles/init-container/Dockerfile
$subject to enable cell information for global CP when issuing the JWT.
=> Add cell name additional property to globally published APIs

samples/employee-portal/hr/hrservice.bal, samples/employee-portal/portal/employee/employeeservice.bal, samples/employee-portal/portal/salary/salaryservice.bal, samples/employee-portal/stock-options/stockservice.bal
Refactor employee-portal services with new header 'x-vick-auth-subject'
=> Refactor employee-portal services with new header 'x-vick-auth-subject'

samples/employee-portal/hr/hrservice.bal
=> Fix hr service response issue

system/scripts/kubeadm/kubeadm-setup.sh
=> Uncommenting update command after adding k8 repository. 

samples/employee-portal/README.md
=> Fix sample image path

system/control-plane/global/vick-apim-artifacts-persistent-volume-claim.yaml, system/control-plane/global/vick-apim-artifacts-persistent-volumes.yaml, system/control-plane/global/vick-apim-gw-ingress.yaml, system/control-plane/global/vick-apim-gw.yaml, system/control-plane/global/vick-apim-persistent-volume-claim-local.yaml, system/control-plane/global/vick-apim-persistent-volumes.yaml, system/control-plane/global/vick-sp-worker-deployment.yaml
=> Add init container to gw.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Update the git base url.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Update status dashboard conf file path.

system/control-plane/global/sp-worker/conf/deployment.yaml, system/control-plane/global/status-dashboard/conf/deployment.yaml
=> Update SP data sources.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Refactor installation script.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Add pubstore ingress.

system/scripts/all-in-one-installer/vick-cleanup.sh
=> Add cleanup script.

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/Dockerfile, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/node-server/config/portal.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/node-server/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/node-server/serve.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/pom.xml, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/public/index.html, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/App.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/AppLayout.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/SignIn.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/TopToolbar.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/color/colorGenerator.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/config/configHolder.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/config/configHolder.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/constants.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/authUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/authUtils.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/httpUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/httpUtils.test.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/queryUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/utils/queryUtils.test.js
> Add support for serving the Observability Portal from NodeJS in a container. Also this contains the new Query Utils class for the different queries supported by the UI.
> Serve the Observability Portal in the Global Plane.
> Add the relevant docker file and NodeJS code for serving the Portal in the container. Also add the relevant maven plugins for building the docker images automatically.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> NPM v6.4.1
> N/A
=> Add Observability Portal Dockerfile

system/scripts/all-in-one-installer/README.md, system/scripts/all-in-one-installer/vick-cleanup.sh, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Added README and fixed typos.

system/control-plane/global/sp-worker/conf/deployment.yaml, system/control-plane/global/status-dashboard/conf/deployment.yaml, system/scripts/all-in-one-installer/vick-cleanup.sh
=> SP JDBC fixes.

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/App.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/AppLayout.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/Cell.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/List.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/MicroService.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/TopToolbar.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/ControlPlane.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/Node.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/Pod.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/index.js
- Structure cell, microservice pages
- Fix left navigation bar height issue
- Add Cell listing table
- Add System metrics pages
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> …
=> Observability Dashboard UI  improvements

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/AppLayout.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/Details.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/List.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/Metrics.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/MetricsGraphs.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservices/Details.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservices/K8sObjects.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservices/List.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservices/Metrics.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservices/MicroService.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/TopToolbar.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/Search.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/index.js
- Adding fixed page header for page title, date range and refresh section
- Adding tab views and structuring cell and microservice pages
=> Observability dashboard UI - Add cell and microservice tab views

system/ingress-controller/handler/handler.go, system/ingress-controller/handler/httpcaller.go, system/ingress-controller/handler/ingress-rule-creator.go, system/ingress-controller/sample/apim-ingress.yaml
> Abstract out the HTTP calls for ease of unit test purposes.
=> Add an abstraction to http calls in the custom ingress

system/control-plane/global/vick-apim-gw.yaml
=> Add UID for APIM.

vendor/github.com/google/go-cmp/LICENSE, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/function/func.go, vendor/github.com/google/go-cmp/cmp/internal/value/format.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/reporter.go, vendor/github.com/google/go-cmp/cmp/unsafe_panic.go, vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
Add missing go-cmp vendor files
=> Add missing go-cmp vendor files

system/ingress-controller/handler/handler.go, system/ingress-controller/handler/handler_test.go, system/ingress-controller/handler/httpcaller.go
> Add tests to HttpCaller default implementation
=> Add http caller tests

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservice/K8sObjects.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/DataTable.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/color/colorGenerator.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview/SidePanelContent.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview/index.css, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview/index.js
-Add overview sidebar
-Fix datatables responsive issue
=> Observability Dashboard - Overview right sidebar

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview/SidePanelContent.js
> overview - Add http traffic stacked bar chart.
=> Observability Dashboard - overview - Add http traffic stacked bar chart

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/MetricsGraphs.js
=> Add Cell Metrics Graphs

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/Node.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/Pod.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/systemMetrics/common/Metrics.js
- Add Pod/Node usage line Graphs
=> Observability Dashboard - Add Pod/Node Usage Graphs

system/control-plane/global/vick-apim-gw.yaml
=> Remove init container mounts.

system/control-plane/global/components/observability/org.wso2.vick.observability.api/src/main/java/org/wso2/vick/observability/api/AggregatedRequestsAPI.java, system/control-plane/global/components/observability/org.wso2.vick.observability.api/src/main/java/org/wso2/vick/observability/api/DependencyModelAPI.java, system/control-plane/global/components/observability/org.wso2.vick.observability.api/src/main/java/org/wso2/vick/observability/api/DistributedTracingAPI.java, system/control-plane/global/components/observability/org.wso2.vick.observability.api/src/main/java/org/wso2/vick/observability/api/siddhi/SiddhiStoreQueryManager.java, system/control-plane/global/components/observability/org.wso2.vick.observability.api/src/main/java/org/wso2/vick/observability/api/siddhi/SiddhiStoreQueryTemplates.java, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/CellList.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/MetricsGraphs.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/Details.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/Metrics.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/MicroserviceList.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservice/Metrics.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservice/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/HealthIndicator.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/color/colorGenerator.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/state/stateHolder.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/toptoolbar/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/overview/SidePanelContent.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/utils/tracingUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/DependencyDiagram.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/timeline/index.js, system/control-plane/global/sp-worker/siddhi/telemetry-app.siddhi
> Add Cell and Micro-service metrics and listing components.
> Add the metrics and listing components and the relevant back-end components
> The commons metrics graphs component was updated to  process and present the metrics. The separate cell and metrics components were altered to fetch the relevant data and pass them to the metrics graphs component. The listing components were update to fetch the data and show the list and other information,
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes …
=> Add Cell And Micro-service Metrics and Listings

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/CellList.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/MetricsGraphs.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/Details.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/MicroserviceList.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservice/Details.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/microservice/index.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/common/HealthIndicator.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/utils/tracingUtils.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/DependencyDiagram.js
> Adding the Health Indicator for the Cells and Microservices
> Fetch data from the back-end for the Helath Indicators and update based on health
> The data is fetched from the back-end for the Health Indicator and based on the error rate the indicator is updated. This also contains several minor bug fixes as well.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A
> N/A
> N/A
> NPM v6.5.0
> N/A
=> Implement Health Indicator for the Cells and Microservices

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Installer script improvements.

build/target/vick.yaml, system/controller/artifacts/08-config.yaml
Add missing analytics config parameters
=> Add missing analytics config parameters

system/scripts/all-in-one-installer/README.md, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Add more emojis.

system/control-plane/global/cloud-generic.yaml, system/control-plane/global/vick-apim-gw.yaml, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> GCP related fixes.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Fix GCP zone issues.

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/cells/cell/Metrics.js, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/pages/tracing/view/index.js, system/control-plane/global/sp-worker/siddhi/telemetry-app.siddhi, system/control-plane/global/sp-worker/siddhi/tracing-app.siddhi, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
> Add some fixes to the Observability UI and the back-end. These fixes address some of the issues in the deployment scripts, Siddhi Apps and the UI.
> Add fixes for the Observability UI and the back-end.
> The Siddhi Apps were edited to filter out the the invalid data and duplicates. The UI was edited to add some minor improvements. The all-in-one scripts was edited to remove unused files and add some of the required files for the Observability UI.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? …
=> Fixes to the Observability UI and SP

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Reformat code.

build/target/vick.yaml, system/controller/artifacts/09-controller.yaml
=> Update vick yaml

system/scripts/all-in-one-installer/README.md, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Update README and script docs.

system/scripts/all-in-one-installer/cellery.env.gcp, system/scripts/all-in-one-installer/cellery.env.kubeadm, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=>  GCP installer updates.

system/control-plane/global/components/observability/org.wso2.vick.observability.ui/package-lock.json, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/components/tracing/view/SequenceDiagram.css, system/control-plane/global/components/observability/org.wso2.vick.observability.ui/src/components/tracing/view/SequenceDiagram.js
> This pull request is made to remove some styling issues faced in the Observability Portal UI.
=> Fix styling issues 

system/controller/pkg/controller/gateway/gateway.go, system/controller/pkg/controller/gateway/resources/deployment.go, system/controller/pkg/controller/gateway/resources/istio_virtual_service.go, system/controller/pkg/controller/gateway/resources/meta.go
Create virtual service for each global API at the ingress
We need an ingress point to each global API. This PR creates a virtual service at Istio's ingress gateway to expose each of these global APIs.
Example: After this PR the following virtual service will be generated when setting up the employee-portal example.
```
Name:         hr--gateway-ingress-virtual-service
Namespace:    default
Labels:       app=hr--gateway
vick.wso2.com/cell=hr
vick.wso2.com/gateway=hr--gateway
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         VirtualService
Metadata:
Creation Timestamp:  2019-01-14T04:45:26Z
Generation:          1
Owner References:
API Version:           vick.wso2.com/v1alpha1
Block Owner Deletion:  true
Controller:            true
Kind:                  Gateway …
```
=> Create virtual service for each global API at ingress

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Env file read fixes.

system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=>  GCP changes.

system/control-plane/global/k8s-artifacts/vick-observability-portal.yaml, system/scripts/all-in-one-installer/vick-setup-all-in-one.sh
=> Add node server configs.

system/controller/pkg/controller/gateway/gateway.go
Replaced cell gateway with micro-gateway
=> Replaced cell gateway with micro-gateway

system/control-plane/cell/components/global-api-updater/src/main/java/org/wso2/vick/apiupdater/UpdateManager.java
> Turn off authentication in micro-gateway
=> Turn off authentication in micro-gateway

build/target/vick.yaml, system/control-plane/cell/components/cell-sts/create-docker-image.sh, system/controller/artifacts/08-config.yaml, system/controller/artifacts/09-controller.yaml
Update sts docker tag to :test
=> Update sts docker tag to :test

build/target/vick.yaml, system/control-plane/global/k8s-artifacts/vick-apim-gw.yaml, system/control-plane/global/k8s-artifacts/vick-apim-pub-store.yaml, system/control-plane/global/k8s-artifacts/vick-observability-portal.yaml, system/control-plane/global/k8s-artifacts/vick-sp-worker-deployment.yaml, system/controller/artifacts/08-config.yaml, system/controller/artifacts/09-controller.yaml
Update docker image tag to :demo-1
=> Update docker image tag to :demo-1

system/control-plane/cell/components/cell-sts/create-docker-image.sh
> Use latest tag to build and push cell STS docker image
=> Use latest tag to build and push cell STS docker image

system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellInterceptorService.java
Fix token validation failure when request reaches through Istio ingress to cell
=> Fix token validation failure when request reaches through Istio ingress to cell

system/controller/pkg/controller/cell/resources/constants.go
=> Update envoy filter listener

system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizationContext.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizationFailedException.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizationHandler.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizationService.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizationUtils.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/AuthorizeRequest.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/opa/OPAAuthorizationContext.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/authorization/opa/OPAAuthorizationHandler.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/model/User.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellInterceptorService.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/sts/service/VickCellStsService.java, system/control-plane/cell/components/cell-sts/src/main/java/org/wso2/vick/auth/cell/utils/LambdaExceptionUtils.java
> Adds authorization layer and initial OPA integration
=> Add authorization layer
